#ifndef ERROR8051_H
#define ERROR8051_H

#define ERR_INVALID_INSTRUCTION     1
#define ERR_INVALID_OPERAND         2
#define ERR_INVALID_REGISTER        3

#define ERR_EXPECTING_INTEGER       4
#define ERR_EXPECTING_REGISTER      5
#define ERR_EXPECTING_IMMEDIATE     11
#define ERR_EXPECTING_IDENTIFIER    12

#define ERR_INTEGER_OUT_OF_RANGE    13
#define ERR_REG_OUT_OF_RANGE        14
#define ERR_INDIRECT_OUT_OF_RANGE   15

#define ERR_UNKNOWN_LABEL           21
#define ERR_DUPLICATE_LABEL         22
#define ERR_ILLEGAL_LABEL           23
#define ERR_TARGET_OUT_OF_RANGE     24

#define ERR_UNSUPPORTED_OPERAND     25
#define ERR_EXTRA_PARAMETER         31

#endif // ERROR8051_H